// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://nilrfowfrvildmxvquew.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pbHJmb3dmcnZpbGRteHZxdWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDM3OTUsImV4cCI6MjA2NDYxOTc5NX0.sLA1ver04HFP2y-tyz309jE654VrvpVFaVA_vg9fnvo"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
